# Generated by Django 5.2.10 on 2026-06-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ai_analyses_this_month_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ai_analyses_this_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
    ]
