# Generated by Django 5.2.10 on 2026-02-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.IntegerField()),
                ('missing_keywords', models.JSONField()),
                ('strengths', models.JSONField()),
                ('suggestions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='jobs.jobapplication')),
            ],
        ),
    ]
