# Generated by Django 5.2.10 on 2026-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aianalysis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
