# Generated by Django 5.2.10 on 2026-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_aianalysis_error_message_aianalysis_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='candidate_level',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='experienced', max_length=20),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='target_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
