# Generated by Django 5.2.10 on 2026-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_aianalysis_candidate_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='tailored_resume_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='tailored_resume_markdown',
            field=models.TextField(blank=True, default=''),
        ),
    ]
