# Generated by Django 5.2.10 on 2026-05-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_aianalysis_tailored_resume_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='resume_template',
            field=models.CharField(choices=[('classic_ats', 'Classic ATS'), ('modern_pro', 'Modern Pro'), ('fresher_project', 'Fresher Project'), ('executive_impact', 'Executive Impact'), ('compact_skills', 'Compact Skills')], default='classic_ats', max_length=40),
        ),
    ]
