# Generated by Django 5.2.10 on 2026-06-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_aianalysis_resume_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='resume_template',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='tailored_resume_generated_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='tailored_resume_markdown',
        ),
    ]
