# Generated by Django 5.2.10 on 2026-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='description_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('extracted', 'Extracted')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
