# Generated by Django 5.2.10 on 2026-02-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
