# Generated by Django 5.2.10 on 2026-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapplication_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='extraction_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('needs_manual', 'Needs Manual Input')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
