# Generated by Django 5.2.10 on 2026-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_extraction_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
