# Generated by Django 5.2.10 on 2026-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobapplication_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_via_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
