# Generated by Django 5.2.10 on 2026-06-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_application_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_note',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_via_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_applied',
        ),
    ]
